### ISSUE TITLE
PDF button extension issue

### ISSUE THREAD

**Issue by typoman** [robofont-mechanic/mechanic-2-server#58]
I know this is not probably the place to post issues relating to a certain extension but this extension hasn't been updated for long time. Maybe the URL should change or it should be removed?

Here is the error I get when I hit the PDF button in the space center RF 3.5b. 
```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python3.7/vanilla/vanillaBase.py", line 503, in action_
    self.callback(sender)
  File "AddButtonPDFToSC.py", line 161, in buttonHitCallback
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by ryanbugden** [comment]
Hey @typoman , maybe we can relocate this issue to [here](https://github.com/thomgb/PDFButtonSpace/issues/4#issue-460509581). In the meantime, I've started testing extensions ([feel free to edit this](https://docs.google.com/spreadsheets/d/1TFzCXNTlYkKwqbWVbWzobmxziiDOjPfZ0h69v3oaSyk/edit?gid=0#gid=0)) that are defunct and either need repairing or removal from Mechanic. So I think it's a larger conversation to have with Frederik.
